envVarGroups:
  - name: database-backups
    envVars:
      # pick the region closest to your database
      # For example, us-west-2 for the Oregon region
      - key: AWS_REGION
        sync: false
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: S3_BUCKET_NAME
        sync: false
      # Looks like "AKIAXXXXXXXXXXXXXXXX"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your Postgres instance
      # For example, 14
      - key: POSTGRES_VERSION
        sync: false

services:
  - name: alumnifire-production-postgres-backup-to-s3
    type: cron
    schedule: "0 3 * * *"
    region: ohio
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: database-backups
      - key: DATABASE_URL
        fromDatabase:
          name: alumnifire-production-postgres
          property: connectionString
      - key: S3_PATH
        value: alumnifire-production-postgres-backups
  - name: alumnifire-production-postgres-backup-to-s3-secondary
    type: cron
    schedule: "0 3 * * *"
    region: ohio
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: database-backups
      - key: DATABASE_URL
        fromDatabase:
          name: alumnifire-production-postgres
          property: connectionString
      - key: S3_PATH
        value: alumnifire-production-postgres-backups
  - name: controlroom-production-postgres-backup-to-s3
    type: cron
    schedule: "0 3 * * *"
    region: ohio
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: database-backups
      - key: DATABASE_URL
        fromDatabase:
          name: controlroom-production-postgres
          property: connectionString
      - key: S3_PATH
        value: controlroom-production-postgres-backups
  - name: controlroom-production-postgres-backup-to-s3-secondary
    type: cron
    schedule: "0 3 * * *"
    region: ohio
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: database-backups
      - key: DATABASE_URL
        fromDatabase:
          name: controlroom-production-postgres
          property: connectionString
      - key: S3_PATH
        value: controlroom-production-postgres-backups
